site_name: Iris Species ML Inference Docs
site_url: https://nextlevelmlops.github.io/iris-ml-classification/
site_description: Documentation for Iris Species ML Inference project.
site_author: NextLevel MLOps
repo_url: https://github.com/nextlevelmlops/iris-ml-classification
repo_name: GitHub
edit_uri: edit/main/docs/
strict: true

theme:
  name: material
  toc:
    depth: 3  # or 2, as desired
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - navigation.top
    - navigation.footer
  icon:
      repo: fontawesome/brands/github
  logo: images/iris_logo.png   # if you have a logo
  favicon: images/favicon.ico

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nextlevelmlops/iris-ml-classification
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/acikgozmehmet-us/
      name: LinkedIn
  copyright: Copyright &copy; 2025 NextLevel MLOps
  announcement:
    type: info
    text: "🚀 Iris ML Inference v1.0 released! See the [release notes](https://github.com/nextlevelmlops/iris-ml-classification)."
    dismissible: true


plugins:
  # - git-revision-date-localized:
  #     enable_creation_date: true
  - search:
      separator: '[\s\-\.]+'
      # prebuild_index: true
      lang:
        - en
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          inventories:
            - https://docs.python.org/3/objects.inv  # Cross-reference Python stdlib

          options:
            # Headings and Navigation
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: false
            show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

            # Members
            members_order: source
            group_by_category: true
            show_submodules: true

            # Docstrings
            docstring_style: sphinx   # or numpy/google , as used in your codebase
            docstring_section_style: table
            merge_init_into_class: true
            show_if_no_docstring: false

            # Signatures
            show_signature: true
            show_signature_annotations: true
            separate_signature: true
            line_length: 80


            # Filters
            filters: ["!^_"]  # Exclude private members
            inherited_members: true

            # Others
            show_source: true
  # - with-pdf  # pip install mkdocs-with-pdf

# nav:
#   - Home: index.md
#   - Tutorials: tutorials.md
#   - How-To Guides: how-to.md
#   - API Reference: reference.md
#   - Explanations: explanation.md
#   - 404: 404.md
#

nav:
  - Home: index.md
  - Tutorials:
      - Getting Started: tutorials/getting-started.md
      - First Model: tutorials/first-model.md
  - How-To Guides:
      - Part-1: how-to/part-1.md
      # - Embed a YouTube Video: how-to/embed-youtube.md
      # - Export Docs as PDF: how-to/export-pdf.md
  - API Reference:
      # - API Overview: reference/index.md
      - app.py: reference/app.md
      - api.py: reference/api.md
      - ui.py: reference/ui.md
      - config.py: reference/config.md
  - Explanations:
      - Architecture: explanation/architecture.md
      - Tips & Tricks: explanation/tips.md
      - Pitfalls: explanation/pitfalls.md


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.superfences
