# https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions
name: ci-mkdocs
on:
  push:
    branches:
      - main
permissions:
  contents: write
env:
  UV_SYSTEM_PYTHON: 1
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v6.3.1
        # with:
        #   python-version: '3.11'

      # Install dependencies using uv (replace with your method if using pyproject.toml)
      - name: Install dependencies
        run: uv pip install mkdocs-material==9.6.15 mkdocstrings[python]==0.29.1

      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force
