name: CI Workflow

on: 
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'main'

jobs:
  ci_job:
    name: CI job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        
      - name: Install uv
        uses: astral-sh/setup-uv@v6.3.1
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Run pre-commit
        run: |
          uv run pre-commit run --all-files

      - name: Run pytest
        run: |
          uv run pytest --disable-warnings --cov=./src  --cov-report=html
          
      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: coverage-html
          path: htmlcov
          

    
    
