name: CI Workflow

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'main'

jobs:
  ci_job:
    name: CI job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v6.3.1
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Run pre-commit
        run: |
          uv run pre-commit run --all-files

      - name: Run pytest
        run: |
          uv run pytest --disable-warnings --cov=./src  --cov-report=html

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: coverage-html
          path: htmlcov

  deploy_job:
    needs: ci_job
    name: Deploy job
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@v0.246.0

      # - name: Deploy to Databricks
      #   env:
      #     DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      #     DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      #   run: |
      #     # Example: update a Databricks Repo in your workspace
      #     databricks bundle deploy
      #     databricks bundle run inference_app

      - name: Authenticate Databricks CLI with Service Principal
        env:
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        run: |
          databricks auth login --client-id $DATABRICKS_CLIENT_ID \
                                --client-secret $DATABRICKS_CLIENT_SECRET \
                                --host $DATABRICKS_HOST \
                                --auth-type oauth

      - name: Deploy to Databricks
        run: |
          databricks bundle deploy
          databricks bundle run inference_app
